In [1]:
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.simplefilter("ignore")

In [3]:
df= pd.read_csv("C:\\Users\\srmve\\Downloads\\User_Data.csv")

In [4]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [6]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [7]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
cat_cols=['Gender']
df[cat_cols]= df[cat_cols].apply(le.fit_transform)
df[cat_cols]

Gender
0         1
1         1
2         0
3         0
4         1
..      ...
395       0
396       1
397       0
398       1
399       0

[400 rows x 1 columns]

In [22]:
x= df.iloc[:,:-2]
x

User ID  Gender  Age  EstimatedSalary
0    15624510       1   19            19000
1    15810944       1   35            20000
2    15668575       0   26            43000
3    15603246       0   27            57000
4    15804002       1   19            76000
..        ...     ...  ...              ...
395  15691863       0   46            41000
396  15706071       1   51            23000
397  15654296       0   50            20000
398  15755018       1   36            33000
399  15594041       0   49            36000

[400 rows x 4 columns]

In [23]:
y=df.iloc[:,-1]
y

0      1
1      1
2      0
3      0
4      1
      ..
395    0
396    1
397    0
398    1
399    0
Name: cat-cols, Length: 400, dtype: int32

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,random_state=0)
x_train

User ID  Gender  Age  EstimatedSalary
250  15810075       0   44            39000
63   15583681       1   32           120000
312  15733964       0   38            50000
159  15598840       0   32           135000
283  15663249       0   52            21000
..        ...     ...  ...              ...
323  15619465       0   48            30000
192  15779581       1   29            43000
117  15591433       1   36            52000
47   15776348       0   27            54000
172  15794661       0   26           118000

[300 rows x 4 columns]

In [26]:
x_test

User ID  Gender  Age  EstimatedSalary
132  15725660       1   30            87000
309  15652400       0   38            50000
341  15776844       1   35            75000
196  15738448       0   30            79000
246  15638003       0   35            50000
..        ...     ...  ...              ...
146  15750839       0   27            96000
135  15578006       1   23            63000
390  15807837       1   48            33000
264  15600379       1   48            90000
364  15654456       1   42           104000

[100 rows x 4 columns]

In [33]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train= scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [34]:
x_train

array([[ 1.67009484, -0.98019606,  0.58164944, -0.88670699],
       [-1.52442817,  1.02020406, -0.60673761,  1.46173768],
       [ 0.59613378, -0.98019606, -0.01254409, -0.5677824 ],
       ...,
       [-1.4150439 ,  1.02020406, -0.21060859, -0.50979612],
       [ 1.19419143, -0.98019606, -1.10189888, -0.45180983],
       [ 1.45259625, -0.98019606, -1.20093113,  1.40375139]])

In [35]:
x_test

array([[ 0.47063377,  1.02020406, -0.54748976,  0.5130727 ],
       [-0.52442049, -0.98019606,  0.15442019, -0.61825566],
       [ 1.16584067,  1.02020406, -0.10879604,  0.14615539],
       [ 0.64432684, -0.98019606, -0.54748976,  0.26846116],
       [-0.71996781, -0.98019606, -0.10879604, -0.61825566],
       [ 1.67056653,  1.02020406, -0.81070599, -1.53554892],
       [-1.09841712, -0.98019606, -0.45975102, -1.68843113],
       [-0.14157044,  1.02020406, -0.0210573 ,  2.25592989],
       [-0.3377833 , -0.98019606, -1.60035469, -0.0678797 ],
       [-0.93083619,  1.02020406,  0.94406888, -0.83229075],
       [-0.02152827,  1.02020406, -0.54748976, -0.6488321 ],
       [ 1.48118568, -0.98019606, -0.72296725, -0.46537345],
       [ 1.11970091,  1.02020406,  0.06668145, -0.46537345],
       [-1.51849682,  1.02020406,  0.24215893,  0.20730828],
       [ 0.74878988,  1.02020406, -1.4248772 ,  0.48249625],
       [ 1.33243009, -0.98019606, -0.37201227,  1.43036596],
       [ 0.944799  ,  1.

In [38]:
from sklearn.naive_bayes import BernoulliNB
model=BernoulliNB(binarize=0.0)

In [39]:
model.fit(x_train,y_train)

BernoulliNB()

In [40]:
y_pred=model.predict(x_test)
y_pred

array([1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1])

In [41]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        51
           1       1.00      1.00      1.00        49

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100



In [43]:
from sklearn.metrics import accuracy_score
accuracy= accuracy_score(y_test,y_pred)*100
print("Accuracy of the model is:",accuracy)

Accuracy of the model is: 100.0


In [47]:
new_data=[[0.47063377,  1.02020406, -0.54748976,  0.5130727]]
prediction=model.predict(new_data)
print(prediction)

[1]
